### ISSUE TITLE
Notes on CSS

### ISSUE THREAD

**Issue by SidTheEngineer** [burleebau/prj-rev-bwfs-dasmoto#2]
Below I've highlighted a couple of areas where we can make minor adjustments to improve the CSS:

**Indentation**
There are a couple of areas in the CSS where our indentation is just slightly off. See if you can go through the code and make the correct adjustments to improve the indentation.

**Brackets**
Right now, the majority of the brackets in the CSS are on the next line after the selector. It is most common to see CSS with the opening bracket on the same line. Example:

```CSS
#brush
{
  background-color: mediumspringgreen;
}
```

vs.

```CSS
#brush {
  background-color: mediumspringgreen;
}
```

**Styling**
The only inconsistency I saw with styling in the project is not making the section titles Helvetica font. If you get this down, the styling will be perferct
